version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./backend:/app
    networks:
      - commercecult_network

networks:
  commercecult_network:
    driver: bridge